/*
export const CLASSES_FETCH_STARTED = 'CLASSES_FETCH_STARTED';
export const CLASSES_FETCH_COMPLETED = 'CLASSES_FETCH_COMPLETED';
export const CLASSES_FETCH_FAILED = 'CLASSES_FETCH_FAILED';

export const CLASS_SELECTED = 'CLASS_SELECTED';
export const CLASS_DESELECTED = 'CLASS_DESELECTED';

export const CLASS_PASSED = 'CLASS_PASSED';

*/
